### ISSUE TITLE
`org-super-links-link` not working when buffer is narrowed

### ISSUE THREAD

**Issue by stefan2904** [toshism/org-super-links#70]
_Not sure if this is a bug or expected:_

**Steps:**

1.) Go to a subtree ASDF
2.) Narrow to that subtree using `org-narrow-to-subtree` (which internally uses `narrow-to-region`)
3.) Use `org-super-links-link` to insert link to remote heading XYZ

**Expected:**

4.) Link to remote heading XYZ is inserted

**What happens:**

4.) Link to current heading ASDF is inserted

![image](https://user-images.githubusercontent.com/527767/157272256-45daad8d-40a1-494b-a676-9613f0b7fa1c.png)

---

I guess the problem exists because `org-super-links--insert-link` at some point tries to seek to the remote XYZ heading (to fetch its ID and DESC, and to insert a BACKLINKS drawer), which it cannot do since the buffer is narrowed. So the marker ends up at the current heading (or another heading that is part of the narrowed buffer) and creates a link to this one instead.

**Other observations:**

- The problem does not exist if you insert a link to a heading in another buffer (which is not narrowed) 
- The problem does not exist if you narrow using `org-tree-to-indirect-buffer` (although it internally also uses `narrow-to-region`, there is still a un-narrowed buffer available for super-link to create the backlink)

**Comment by toshism** [comment]
Thanks! definitely a bug. I'll take a look.

**Comment by toshism** [comment]
@stefan2904 finally had a chance to take a look at this. it should be fixed now. 

thanks!

**Comment by stefan2904** [comment]
First, thanks for the fix and sorry for my late reply!

I just noticed this did not work because I still had `20210620.1453` installed. Apparently quelpa was broken or I previously had it manually installed.
I now have `20220714.211740`. 

Unfortunately there is still a problem, but it is slightly different now: when I insert the link, the buffer widens itself (and then inserts the correct link). This is less of a problem but still not as expected.

For the record, this happens if the target heading is in the same file (which was a problem before) as well as if its in another file (which was not a problem before if I remember correctly). 


**Steps:**

1.) Go to a subtree ASDF
2.) Narrow to that subtree using `org-narrow-to-subtree` (which internally uses `narrow-to-region`)
3.) Use `org-super-links-link` to insert link to remote heading XYZ

**Expected:**

4.) Link to remote heading XYZ is inserted. Buffer stays narrowed to heading ASDF

**What happens:**

4.) Link to remote heading XYZ is inserted. Buffer *is widened again* (whole file becomes visible).

**Comment by stefan2904** [comment]
Hm, the fix in bd91f1ac3a5dc2650ade39b8312da4bbd045a480 looks like this is intentional. Which makes sense given that this quickly fixes the issue described by me. ;-)

I don't know enough elisp to fully understand that, but as far as I figure, the problem is that your module cannot access the text which is currently not visible, thus neither read it (to get its name/ID), nor update it (to insert backlinks). This is the reason why it works if the link target is in another (open?) buffer, but not in the same buffer (which is narrowed).

I think a solution for this I saw in another module is some construct that creates a temporary indirect clone of the current buffer, widens it and does its operations there, without touching the original (visible) buffer.  Something like [this Stackoverflow answer](https://emacs.stackexchange.com/a/2196/33705); not sure how to best do it in the background.

An example that comes to my mind is `org-capture`, which uses an indirect-buffer.
